### PR TITLE
plugin-excalidraw: re-import the forked plugin and update it to current APIs

### PR DESCRIPTION
**Pull request by richburdon**
Copies [dxos/plugin-excalidraw](https://github.com/dxos/plugin-excalidraw) back into `packages/plugins` and brings it up to date with everything `plugin-sketch` absorbed since the plugin was extracted in #11050.

## Why

The standalone fork builds against published `@dxos/*@0.8.4-main.*` and had drifted from `main`: it still used `meta.id`, `Type.object`, string operation keys, hand-rolled surface filters, `@dxos/echo-db`, and a vendored copy of the Automerge store adapter. None of that compiles in-repo today.

## What changed

Ported forward, mirroring `plugin-sketch`:

- **Meta** — from `dx.config.ts` via `Plugin.getMetaFromConfig`; `meta.id` → `meta.profile.key` throughout.
- **Schema** — `Type.makeObject` classes keyed by `DXN.make(typename, version)`; `SystemTypeAnnotation` → `HiddenAnnotation`.
- **Operations** — DXN keys, `Type.getSchema` for output, `Type.getTypename` for the create-object entry; dropped the removed `hidden` input on `SpaceOperation.AddObject`.
- **Surfaces** — `AppSurface.oneOf(AppSurface.object(Article | Section | Slide, Excalidraw))` role tokens instead of a hand-written type guard.
- **Settings** — `@dxos/react-ui-form`'s `Settings` export is gone, so the panel is rebuilt on `Form.Root variant='settings'` + `Form.FieldSet`, with labels/descriptions moved into schema annotations. Moved from `components/` to `containers/` (matches markdown), and the now-redundant `settings.*` translation keys were removed.
- **Store adapter** — deleted the vendored `src/util/automerge-*` in favour of `@dxos/echo-doc`'s `AbstractStoreAdapter` (the generalised version of the same code, with sync `open()` returning a disposer); `@dxos/echo-db` → `Doc.createAccessor` / `@dxos/echo-client`.
- **Misc** — `composable`/`composableProps` now come from `@dxos/react-ui`; `SketchContainer`/`SketchSettings` renamed to `ExcalidrawArticle`/`ExcalidrawSettings`.
- **Packaging** — `workspace:*` deps, `moon.yml`, `vite.base.config` entries (standalone `composerPlugin` vite config and `vitest.config.ts` dropped), tsconfig references, FSL licence, `ExcalidrawPlugin.test.ts` activation smoke test.

## Reviewer notes

- **`langium@3.3.1` added to `trustPolicyExclude`** in `pnpm-workspace.yaml`. `pnpm install` refuses it as a trust downgrade — it is a transitive of `@excalidraw/excalidraw` via `@mermaid-js/parser` and has no provenance attestation, the same situation as the existing `mermaid@10.9.4` entry. Flagging it explicitly since it is a supply-chain exception.
- **The package is `private: true`** per the new-package rule (publishing waits on a trusted publisher). The postinstall toolbox still added it to the changesets fixed group, which is correct — `privatePackages.version` is `true`, so it is versioned but not published. No changeset: nothing consumer-visible ships.
- The plugin is **not registered in `composer-app`** — it wasn't before removal either.
- Settings are declared but not yet consumed by the canvas (`autoHideControls` / `gridType` were already inert in the fork); wiring them is follow-up work.

## Verification

`build`, `lint`, the activation test, and both storybook stories pass. Ran the plugin storybook locally: the Excalidraw editor mounts and draws (adapter `save()` clean on pointer-up) and the settings form renders from the schema annotations.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **New Features**
  * Added the Excalidraw plugin for creating, editing, and viewing collaborative drawings in articles, sections, and slides.
  * Introduced Excalidraw settings (grid type: mesh or dotted, with optional auto-hide controls) with localized UI labels.
* **Documentation**
  * Added plugin documentation, including license information and contribution/resources links.
* **Tests**
  * Added automated tests to verify plugin activation, plus Storybook coverage for the drawing and settings views.
* **Chores / Tooling**
  * Added Storybook setup and a dedicated dev launch profile for the plugin.

### CODE REVIEW

File: packages/plugins/plugin-excalidraw/src/hooks/adapter.ts [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+      .filter(Boolean) as ExcalidrawElement[];
+    const deleted = Array.from(this._deleted);
+    log('save', { updated: updated.length, deleted: deleted.length });
+    if (updated.length || deleted.length) {
+      super.updateDatabase({ updated, deleted });
+    }
+
+    this._modified.clear();
+    this._deleted.clear();
+  }
```
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/src/hooks/adapter.ts:69]: Fixed in 182250c20b (first pass c1ef7feb4d) — now `.filter(isNonNullable)`. Also removed the two casts you didn't flag: the buffered-elements ref in `ExcalidrawArticle` is typed `readonly ExcalidrawElement[]` so the imperative-API replay needs no cast. The package is now cast-free.

File: packages/plugins/plugin-excalidraw/src/containers/ExcalidrawArticle/ExcalidrawArticle.stories.tsx [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+const meta = {
+  title: 'plugins/plugin-excalidraw/containers/ExcalidrawArticle',
+  component: ExcalidrawArticle as any,
+  render: DefaultStory,
+  decorators: [withTheme(), withLayout({ layout: 'fullscreen' })],
+  parameters: {
+    layout: 'fullscreen',
+  },
+} satisfies Meta<typeof DefaultStory>;
```
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/src/containers/ExcalidrawArticle/ExcalidrawArticle.stories.tsx:28]: Fixed in c1ef7feb4d. `component: ExcalidrawArticle` alone doesn't typecheck — `satisfies Meta<typeof DefaultStory>` then demands `args` that the render wrapper supplies itself. Took your second option and dropped `component`, matching the repo's existing render-wrapper stories (e.g. `AgentProperties.stories.tsx`).

File: packages/plugins/plugin-excalidraw/src/hooks/useStoreAdapter.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+      }
+
+      forceUpdate({});
+
+      return () => {
+        adapter.close();
+      };
+    },
+    [object, canvasSnapshot],
+  );
```
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/src/hooks/useStoreAdapter.ts:71]: Fixed in 182250c20b. Confirmed the concern is real and worse than described: `useAsyncEffect` awaits the callback inside a `setTimeout` with no catch, so a rejected load escapes as an unhandled rejection — which this repo explicitly forbids. Wrapped the load in try/catch with a `log.warn`.

File: packages/plugins/plugin-excalidraw/src/types/Excalidraw.ts [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+  const canvas = Obj.make(Canvas, { schema, content });
+  return Obj.make(Excalidraw, { ...props, canvas: Ref.make(canvas) });
+};
+
+/**
+ * Type guard for {@link Excalidraw} objects. `Obj.instanceOf` is typename-aware so
+ * plugin-sketch's `Sketch` — which shares the structural shape (`name` + `canvas` ref) —
+ * does not false-positively match here.
+ */
+export const isExcalidraw = (object: any, _schema?: string): object is Excalidraw => Obj.instanceOf(Excalidraw, object);
```
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/src/types/Excalidraw.ts]: Fixed in 182250c20b — `(object: unknown)`, and the unused `_schema` parameter is gone (no callers pass it).

File: packages/plugins/plugin-excalidraw/src/translations.ts [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+      [Type.getTypename(Excalidraw.Excalidraw)]: {
+        'typename.label': 'Excalidraw',
+        'typename.label_zero': 'Excalidraws',
+        'typename.label_one': 'Excalidraw',
+        'typename.label_other': 'Excalidraws',
+        'object-name.placeholder': 'New excalidraw',
+        'add-object.label': 'Add excalidraw',
+        'rename-object.label': 'Rename excalidraw',
+        'delete-object.label': 'Delete excalidraw',
+        'object-deleted.label': 'Excalidraw deleted',
```
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/src/translations.ts]: Fixed in 182250c20b. Agreed — Excalidraw is a brand name, unlike plugin-sketch's "New sketch" where lowercase is correct.

File: packages/plugins/plugin-excalidraw/README.md [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+
+- [Website](https://dxos.org)
+- [Developer Documentation](https://docs.dxos.org)
+- Talk to us on [Discord](https://dxos.org/discord)
+
+## Contributions
+
+Your ideas, issues, and code are most welcome. Please take a look at our [community code of conduct](https://github.com/dxos/dxos/blob/main/CODE_OF_CONDUCT.md), the [issue guide](https://github.com/dxos/dxos/blob/main/CONTRIBUTING.md#submitting-issues), and the [PR contribution guide](https://github.com/dxos/dxos/blob/main/CONTRIBUTING.md#submitting-prs).
+
+License: [FSL-1.1-Apache-2.0](./LICENSE) Copyright 2023 © DXOS
```
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/README.md:15]: Skipping — not a conflict, this is the repo-wide convention. Every plugin README ends "Copyright 2023 © DXOS" while its LICENSE says "Copyright 2026 DXOS" (checked plugin-sketch, plugin-mermaid, plugin-board). Diverging here would make this package the odd one out; if the convention is wrong it should change repo-wide, not in this PR.

File: packages/plugins/plugin-excalidraw/src/hooks/useStoreAdapter.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (richburdon) [reply packages/plugins/plugin-excalidraw/src/hooks/useStoreAdapter.ts:71]: Also applied the two useStoreAdapter nitpicks from the review body in 3a8d0af9bd: lazy `useState(() => new ExcalidrawStoreAdapter(options))` (the article re-renders on every pointer down/up, so the eager form allocated and discarded an adapter per render) and the array-hole form `const [, forceUpdate]`.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

**Comment by richburdon** [comment]
Nitpicks from the review body (no inline threads) — 2 of 3 applied in 3a8d0af9bd:

- **Lazy `useState` initializer** — applied. `ExcalidrawArticle` re-renders on every pointer down/up, so the eager form allocated and discarded an adapter per render.
- **Single-letter `_` binding** — applied, now `const [, forceUpdate] = useState({})`.
- **Move the `moduleId` helper below `describe`** — skipped. All 53 `*Plugin.test.ts` activation tests in `packages/plugins` declare `moduleId` above the suite; it reads as suite configuration (which the guideline puts at the top) rather than a helper. Diverging in this one file would make it the outlier — worth a repo-wide change if the guideline is meant to cover it.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

**Comment by wittjosiah** [comment]
For context on the "the standalone fork had drifted" premise: the fork has now been brought up to date. dxos/plugin-excalidraw#8 landed as [`c99bb3a`](https://github.com/dxos/plugin-excalidraw/commit/c99bb3a790a403c4c030b01a0d39a95431aa879d), pinned to `dxos/dxos@6be8009`, and it follows most of what this PR does:

- meta from `dx.config.ts` via `Plugin.getMetaFromConfig`, `meta.profile.key` throughout
- `Type.makeObject` schema in the class form, DXN-keyed operations, `HiddenAnnotation` on the canvas
- `AppSurface.oneOf(AppSurface.object(...))` role tokens instead of a hand-written type guard
- settings rebuilt on `Form.Root variant='settings'` + `Form.FieldSet`, labels moved to schema annotations
- the vendored automerge store adapter replaced by `@dxos/echo-doc`'s `AbstractStoreAdapter` + `Doc.createAccessor`, which also drops the direct `@automerge/automerge` dependency
- the removed `hidden` input on `SpaceOperation.AddObject` dropped
- an `ExcalidrawPlugin.test.ts` activation test

It should also stay current from here: the repo now has a nightly workflow that repins the SDK catalog to the latest `dxos/dxos` main build, rebuilds, and opens an auto-merging PR, gated on a CI pipeline that runs format, lint, build and test.

Two things noticed while porting, both about this branch rather than the fork:

1. **`CollectionItemAnnotation` is missing from the `Excalidraw` type here.** `plugin-sketch` sets it (along with `CardAnnotation`), and now that `hidden` is gone from `AddObject` it is what keeps new objects out of the database section's `types/` subtree — `AppNode.isCollectionItem` reads it to decide collection eligibility. Added in the fork as [`744b55e`](https://github.com/dxos/plugin-excalidraw/commit/744b55e77428410f39abe36637e58bf6688906b1); worth adding here too, and possibly `CardAnnotation` with it.

2. **`@dxos/react-ui-stack` no longer exists on main.** Not an issue for this branch, which doesn't depend on it — noting it only because it 404'd the fork's install outright when the pin moved, so anything else still referencing it will break the same way.

Separately, and unrelated to this PR: `@dxos/cli@0.10.0` appears broken as published. The launcher execs a platform binary that ships without the executable bit (`-rw-r--r--`, so `npm i -g @dxos/cli && dx …` fails with `EACCES`), and after chmod every invocation — `--version` included — fails with `Cannot find module '@dxos/react-ui-attention/types' from '/$bunfs/root/bin.js'`. Flagging here since it blocks `dx registry publish` for community plugins; happy to move it to an issue if that is a better home.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by richburdon** [comment]
Thanks @wittjosiah — the `CollectionItemAnnotation` catch is a real regression in this branch, now fixed in b2e8e2d871.

**1. `CollectionItemAnnotation` — fixed.** Confirmed the mechanism: `AppNode.isCollectionItem` requires the annotation, and without it `CollectionModel` takes the `Database.add(object)` branch, so new objects land under `types/<slug>` instead of the target collection. This branch dropped `hidden: true` from `AddObject` because the input no longer exists, but never added what replaced it — my miss. Added on the `Excalidraw` type (also pulled `@dxos/schema` into the package deps and tsconfig references).

**`CardAnnotation` — deliberately not added.** It marks a type whose collection tiles render a body through the `AppSurface.CardContent` surface, and this plugin contributes no such surface (plugin-sketch sets it *and* ships `SketchCard`). Setting it here would promise a preview body nothing renders. Adding an `ExcalidrawCard` container mirroring `SketchCard` is a reasonable follow-up — happy to include it here if you'd prefer it in this PR.

**2. `@dxos/react-ui-stack`** — no action needed; hit the same 404 while porting and dropped it from the dependency set. This branch has no reference to it.

**On the premise:** you're right that the fork has caught up, which makes "in-repo copy vs. fork + nightly repin" a real fork in the road rather than a formality — and that's a maintainer call, not one I should make inside this PR. Worth noting the two aren't equivalent in kind: in-repo means API changes like the `AddObject`/`CollectionItemAnnotation` one get caught by `Check` at the commit that makes them, whereas the fork finds out on the next nightly repin. The flip side is that this package is `private: true` and unregistered in composer-app, so in-repo it ships nothing today. Happy to close this in favour of the fork if that's the direction.

**On `@dxos/cli@0.10.0`:** agreed it belongs in its own issue rather than this PR — unrelated to these changes, and a broken published launcher blocking `dx registry publish` deserves its own thread. I haven't reproduced it; say the word and I'll file one with your details.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

**Comment by wittjosiah** [comment]
To make the point I left implicit above: my suggestion would be to **close this in favour of the standalone repo** — though that is the author's call, not mine.

The reasoning:

- The drift this PR exists to fix has been addressed at its source. `dxos/plugins` (formerly `dxos/plugin-excalidraw`) is now current with `dxos/dxos@6be8009` and has a nightly workflow that repins the SDK catalog, rebuilds, and auto-merges when CI is green — gated on format, lint, build and test, plus a module-activation test.
- Landing both leaves two copies of the same plugin maintained separately, and this PR is itself the evidence of how quickly that diverges. The next divergence starts the day both are on `main`.
- Per this PR's own description the re-imported copy is not registered in `composer-app`, so closing it does not remove anything users have today.
- `.github/RELEASE-SPEC.md` §6 argues to bias toward not splitting, since every cut edge is a versioning cost paid every release. That cost is already being paid for the standalone; maintaining both pays it twice without a corresponding benefit.

The honest counterargument, which is why this is a judgement call rather than an obvious one: in-monorepo the plugin gets `workspace:*` deps and none of the standalone's overhead — no pkg.pr.new pins that expire, no external-catalog-versus-SDK version matching, no nightly to babysit. Those are real, recurring costs we hit repeatedly getting the fork current. If the intent is for this plugin to ship with the SDK rather than as a community plugin on its own cadence, keeping it here is the better answer and the standalone should be the thing that goes away. That is the question worth deciding, and only you can.

Either way, the two gaps I noted above (`CollectionItemAnnotation`, and `@dxos/react-ui-stack` no longer existing on main) apply to whichever copy survives. The `@dxos/cli@0.10.0` packaging problem is independent of this decision and shouldn't be lost if this PR closes — happy to open it as its own issue.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by richburdon** [comment]
Thanks — the close-versus-land question is with @richburdon, so leaving this open pending that decision rather than closing it unilaterally. The branch is green on b2e8e2d871 and I'm not pushing further changes to it meanwhile.

Two notes for whoever picks it up:

- Checked `.github/RELEASE-SPEC.md` §6 — the "bias toward not splitting" citation holds (Dependency & cycle policy, item 8). Worth adding that the same section's repo-split plan lists `plugins/*` under Repo B (`composer`), not `dxos`, so in-repo plugins are slated to leave this repo eventually regardless. That cuts toward your recommendation rather than against it.
- `CollectionItemAnnotation` is now in both copies — 744b55e in the standalone, b2e8e2d871 here — so it isn't stranded whichever survives.

On `@dxos/cli@0.10.0`: please do open it as its own issue. I haven't reproduced it and you have the details firsthand, so it's better filed by you than relayed by me.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_
